### ISSUE TITLE
bug in base.py

### ISSUE THREAD

**Issue by N-tab** [arklual/geometry#5]
@arklual , in file base.py functions of calculation cos, sin and tan working wrong... In my branch I solved this problem, so take a look and tell me if everything is done correctly.

**Comment by arklual** [comment]
@N-tab Ok, it must be right, I'm so stupid:). Please create a pull request to the main branch(only main.py file).

**Comment by arklual** [comment]
Can you also fix similar bug in radian sin, cos, tan functions in base.py(class Angle)

**Comment by N-tab** [comment]
@arklual already

**Comment by arklual** [comment]
![Screenshot_20211208-173106_GitHub.png](https://user-images.githubusercontent.com/60625451/145225996-3a73402d-2a52-4c4d-880b-efd8db3bbdef.png)

**Comment by N-tab** [comment]
@arklual Function, wich takes radians as argument working normally (I checked).

**Comment by arklual** [comment]
@N-tab This functions don't take any arguments. In the variable ___value_ we keep angle value in **degrees**

**Comment by N-tab** [comment]
@arklual I admit I made a mistake in argumentation, but it does not change the meaning... 
![IMG_20211208_175030](https://user-images.githubusercontent.com/65714812/145229516-ddad03da-0f20-4cc0-bedf-3c7e8e00d76d.jpg)
![IMG_20211208_174833](https://user-images.githubusercontent.com/65714812/145229519-d085ae11-dec8-439b-9af6-867af8da6d8b.jpg)

As proof, I will give the calculations.

**Comment by arklual** [comment]
Hmm, I just now realized that we can't convert sin, cos and tan to degrees. I think this functions are useless and unnecessary

**Comment by N-tab** [comment]
I think similar
